name: build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build (Debug)
        run: msbuild src/DelApp.sln /t:Rebuild /p:Configuration=Debug /warnaserror

      - name: Build (Release)
        run: msbuild src/DelApp.sln /t:Rebuild /p:Configuration=Release /warnaserror
